### ISSUE TITLE
Is it possible to see the KMeans applied ?

### ISSUE THREAD

**Issue by wassilakrouche** [PetrKorab/Clustering-Textual-Data-with-Word2Vec#1]
Hello @PetrKorab,

Currently working on a similar idea i followed your approach and I would really like to see how the KMeans is applied here ? 
Is it possible to provide the kmeans as well please ?

Thanks.

**Comment by PetrKorab** [comment]
Hello Wassila, 
I used Orange (part of Anaconda) because it was more efficient that coding it in python I uploaded the Orange canvas: https://github.com/PetrKorab/Clustering-Textual-Data-with-Word2Vec

**Comment by wassilakrouche** [comment]
Thank you for your answer !
So when you upload the "kmeans-clustering.xlsx" it is generated in orange ?
Thanks for the upload

**Comment by PetrKorab** [comment]
Yes, completely. Here you have the data: https://www.dropbox.com/home/Wassila%20-%20github

**Comment by wassilakrouche** [comment]
Thank you so much !
